sudo: false
language: ruby
before_install: gem install bundler -v 1.12.5
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - jruby-18mode
  - jruby-19mode
  - jruby-9.0.5.0
  - jruby-9.1.1.0
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: jruby-9.1.1.0
    - rvm: jruby-18mode
    - rvm: jruby-19mode
